# 机器人appId
appid: "*********"
# 机器人安全密钥
secret: "*********"
# 机器人名字
botName: "neko"
# 用户消息的最大记录数量
userMessageMaxLen: 10
# 群/频道消息的最大记录数量
groupMessageMaxLen: 5
# 每个记录的消息的最大有效时间（ s ）
userMessageMaxTtl: 7200
# 是否隐藏模型服务，如果隐藏则无法使用模型
needHiddenModule: False
# 模型服务sk
model_server_sk: '********'
# 模型服务id
model_server_id: 49
# 模型的 type 参数 请参考：https://www.lingyuzhao.top/b/Article/377388518747589#model%20%E5%8F%82%E6%95%B0
model_server_type: 'cat_neko'
# 群组模型下的 type 参数
model_server_type_group: 'cat_neko_group'
# 模型的 model 参数 请参考：https://www.lingyuzhao.top/b/Article/377388518747589#type%20%E5%8F%82%E6%95%B0
model_server_model: 'model01'
# 可处理图像的模型 model 参数 请参考：https://www.lingyuzhao.top/b/Article/377388518747589#type%20%E5%8F%82%E6%95%B0
model_server_model_image: 'model03'
# 翻译服务sk
translate_server_sk: '********'
# 翻译服务id
translate_server_id: 46
# jvm 的 jar 插件
jvm_jars:
  - "/opt/app/qq-neko/qq-ai-bot-codeBook/lib/lyMbl-shell.jar"
# jvm 的dll库文件路径 如果启用此路径，则机器人会获得更丰富的功能 如发送邮件
# jvm_dll: "/opt/app/jdk-17.0.12/lib/server/libjvm.so"